// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserManagement.Repository;

namespace UserManagement.Repository.Migrations
{
    [DbContext(typeof(UserManagementContext))]
    partial class UserManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UserManagement.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Designation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            AddressId = 1,
                            Designation = "Developer",
                            ImagePath = "",
                            JoiningDate = new DateTime(2022, 6, 14, 19, 34, 28, 917, DateTimeKind.Local).AddTicks(9200),
                            Name = "John"
                        },
                        new
                        {
                            UserId = 2,
                            AddressId = 2,
                            Designation = "Project Manger",
                            ImagePath = "",
                            JoiningDate = new DateTime(2022, 6, 13, 19, 34, 28, 918, DateTimeKind.Local).AddTicks(53),
                            Name = "Mark"
                        },
                        new
                        {
                            UserId = 3,
                            AddressId = 3,
                            Designation = "Team Lead",
                            ImagePath = "",
                            JoiningDate = new DateTime(2022, 6, 12, 19, 34, 28, 918, DateTimeKind.Local).AddTicks(65),
                            Name = "Smith"
                        },
                        new
                        {
                            UserId = 4,
                            AddressId = 1,
                            Designation = "Developer",
                            ImagePath = "",
                            JoiningDate = new DateTime(2022, 5, 15, 19, 34, 28, 918, DateTimeKind.Local).AddTicks(66),
                            Name = "Emma"
                        },
                        new
                        {
                            UserId = 5,
                            AddressId = 2,
                            Designation = "Developer",
                            ImagePath = "",
                            JoiningDate = new DateTime(2022, 4, 15, 19, 34, 28, 918, DateTimeKind.Local).AddTicks(89),
                            Name = "Sophia"
                        },
                        new
                        {
                            UserId = 6,
                            AddressId = 3,
                            Designation = "HR",
                            ImagePath = "",
                            JoiningDate = new DateTime(2019, 6, 15, 19, 34, 28, 918, DateTimeKind.Local).AddTicks(91),
                            Name = "Olivia"
                        },
                        new
                        {
                            UserId = 7,
                            AddressId = 1,
                            Designation = "Developer",
                            ImagePath = "",
                            JoiningDate = new DateTime(2021, 6, 15, 19, 34, 28, 918, DateTimeKind.Local).AddTicks(101),
                            Name = "Liam"
                        },
                        new
                        {
                            UserId = 8,
                            AddressId = 2,
                            Designation = "Developer",
                            ImagePath = "",
                            JoiningDate = new DateTime(2022, 6, 13, 19, 34, 28, 918, DateTimeKind.Local).AddTicks(103),
                            Name = "Benjamin"
                        },
                        new
                        {
                            UserId = 9,
                            AddressId = 3,
                            Designation = "HR",
                            ImagePath = "",
                            JoiningDate = new DateTime(2019, 6, 15, 19, 34, 28, 918, DateTimeKind.Local).AddTicks(104),
                            Name = "Elijah"
                        },
                        new
                        {
                            UserId = 10,
                            AddressId = 1,
                            Designation = "Developer",
                            ImagePath = "",
                            JoiningDate = new DateTime(2022, 5, 15, 19, 34, 28, 918, DateTimeKind.Local).AddTicks(106),
                            Name = "John"
                        },
                        new
                        {
                            UserId = 11,
                            AddressId = 2,
                            Designation = "Developer",
                            ImagePath = "",
                            JoiningDate = new DateTime(2022, 4, 15, 19, 34, 28, 918, DateTimeKind.Local).AddTicks(108),
                            Name = "Mark"
                        },
                        new
                        {
                            UserId = 12,
                            AddressId = 3,
                            Designation = "Developer",
                            ImagePath = "",
                            JoiningDate = new DateTime(2022, 3, 15, 19, 34, 28, 918, DateTimeKind.Local).AddTicks(109),
                            Name = "Smith"
                        });
                });

            modelBuilder.Entity("UserManagement.Model.UserAddress", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PinCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressId");

                    b.ToTable("UserAddress");

                    b.HasData(
                        new
                        {
                            AddressId = 1,
                            City = "New York",
                            Country = "USA",
                            PinCode = "12345",
                            State = "USA State",
                            Street = "Test Street Address USA"
                        },
                        new
                        {
                            AddressId = 2,
                            City = "Muscat",
                            Country = "Oman",
                            PinCode = "445778",
                            State = "Oman State",
                            Street = "Test Street Address Oman"
                        },
                        new
                        {
                            AddressId = 3,
                            City = "Dubai",
                            Country = "UAE",
                            PinCode = "98766",
                            State = "UAE State",
                            Street = "Test Street Address UAE"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
